export const DRAWER_TYPES = {
  SECTION_LAYOUT_PICKER_DRAWER: "SECTION_LAYOUT_PICKER_DRAWER",
  ROW_LAYOUT_PICKER_DRAWER: "ROW_LAYOUT_PICKER_DRAWER",
  ENTER_SECTION_INFO_DRAWER: "ENTER_SECTION_INFO_DRAWER",
};
