export const DRAWER_TYPES = {
  SECTION_LAYOUT_PICKER_DRAWER: "SECTION_LAYOUT_PICKER_DRAWER",
  ROW_LAYOUT_PICKER_DRAWER: "ROW_LAYOUT_PICKER_DRAWER",
  ENTER_SECTION_INFO_DRAWER: "ENTER_SECTION_INFO_DRAWER",
  ELEMENT_PICKER_DRAWER: "ELEMENT_PICKER_DRAWER",
};

export const ELEMENT_TYPES = {
  NUMBER_INPUT_ELEMENT: "NUMBER_INPUT_ELEMENT",
  TEXT_INPUT_ELEMENT: "TEXT_INPUT_ELEMENT",
  DATE_PICKER_INPUT_ELEMENT: "DATE_PICKER_INPUT_ELEMENT",
};
